#!/bin/bash

echo "🎉 USUÁRIOS CRIADOS COM SUCESSO NO BANCO DE DADOS!"
echo "=================================================="
echo ""
echo "📋 CREDENCIAIS DE LOGIN DISPONÍVEIS:"
echo ""
echo "👑 ADMINISTRADORES (ADMIN):"
echo "  📧 admin@igemstock.com"
echo "  👤 Username: admin"
echo "  🔑 Password: admin123"
echo ""
echo "  📧 gerente@igemstock.com"
echo "  👤 Username: gerente"
echo "  🔑 Password: ger123"
echo ""
echo "🛡️  MODERADORES (MODERATOR):"
echo "  📧 moderator@igemstock.com"
echo "  👤 Username: moderator"
echo "  🔑 Password: mod123"
echo ""
echo "  📧 supervisor@igemstock.com"
echo "  👤 Username: supervisor"
echo "  🔑 Password: super123"
echo ""
echo "👤 USUÁRIOS COMUNS (USER):"
echo "  📧 user@igemstock.com"
echo "  👤 Username: user"
echo "  🔑 Password: user123"
echo ""
echo "  📧 operador@igemstock.com"
echo "  👤 Username: operador"
echo "  🔑 Password: op123"
echo ""
echo "⚠️  LEMBRE-SE:"
echo "• Essas credenciais são apenas para desenvolvimento"
echo "• Nunca use em produção"
echo "• Todas as senhas são criptografadas no banco"
echo ""
echo "🚀 Agora você pode fazer login no sistema com qualquer uma dessas credenciais!"
