FROM node:20 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build --prod

FROM nginx:1.25

COPY --from=builder /app/dist/your-angular-app-name /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
